### ISSUE TITLE
custom celltag reference for alignment

### ISSUE THREAD

**Issue by lb15** [morris-lab/CellTagWorkflow#2]
Hi!
Thanks for the great workflow! For the custom reference used in the cellranger count function, do you add the entire celltag plasmid sequence or only a small portion containing the celltag barcode and perhaps the GFP sequence?

Thanks!

**Comment by babiddy** [comment]
Hi! 
Thanks for the feedback! It is not necessary to add the whole plasmid sequence to the reference. For our custom reference, we added the 3' UTR sequence of the CellTag transcript, the GFP Coding Sequence of the CellTag transcript, and the 3' UTR of the FoxA1/HNF4a construct used for reprogramming. Adding these sequences to the reference allowed us to quantify them using cellranger count and includes them as genes in the final gene expression matrix, but is not required for the workflow as we can still extract the CellTag sequences from the data.

Best,
Brent

**Comment by lb15** [comment]
Hi Brent,

Thanks for your response, that's helpful! I figured that without the 3' UTR sequence with the CellTag transcript added to the reference genome, the celltag reads would be thrown out and not appear in the BAM file? Or are those reads flagged as non-aligned but kept in the file so you can pull them out in the workflow? Thanks for your help!

Sincerely,
Lauren

**Comment by babiddy** [comment]
Hi Lauren,

No problem! From my understanding cellranger outputs all of the reads to the BAM file. This [article](https://kb.10xgenomics.com/hc/en-us/articles/360004689632-How-do-I-identify-the-unmapped-reads-in-my-Cell-Ranger-or-Long-Ranger-output-) from 10x explains how all of the unmapped reads can be identified from the cellranger BAM file. Also when extracting the CellTag sequences, we can see that some, but not all of the reads, are mapped to the 3' UTR sequence. With the workflow, we have been able to pull out both mapped and unmapped CellTag reads. I hope this helps!

Best,
Brent

**Comment by lb15** [comment]
ah, great! thanks for the info!
